#!/bin/bash

# -- CONFIG --

KEYBOARD="de-latin1-nodeadkeys"

BOOT_PART_END="100MiB"
ROOT_PART_END="20GiB"
SWAP_PART_END="24GiB"


# -- SET KEYBOARD LAYOUT --

echo -e "\nKeyboard layout: $KEYBOARD"
sudo loadkeys $KEYBOARD


# -- CHECK FIRMWARE --

if [[ $(ls /sys/firmware/efi/efivars > /dev/null 2>&1) ]]; then
    echo -e "\nFirmware: UEFI"
else
    echo -e "\nFirmware: BIOS"
fi


# -- SET SYSTEM CLOCK --

timedatectl set-ntp true


# -- SHOW DISKS --

echo -e "\nBlock devices:"
lsblk


# -- SELECT DISK --

echo -e "\n"

while true
do
    read -p "Enter target block device (e.g. sda): " device

    if [[ ${#device} -ne 3 ]]; then
        echo -e "Please enter a device from the list."
        continue
    fi

    if [[ $device != sd* ]]; then
        echo -e "Please enter a device from the list."
        continue
    fi

    check=$(lsblk | grep $device)
    if [[ -z "${check// }" ]]; then 
        echo -e "Please enter a device from the list."
        continue
    fi

    break
done


# -- CONFIRMATION --

while true
do
    read -p "Are you sure you want to use /dev/$device? (y/N) " answer

    case $answer in
        [yY]* ) break;;
        [nN]* ) exit;;
        * ) continue;;
    esac
done


# -- PARTITION THE DISK --

echo -e "Partition /dev/$device"

fdisk /dev/$device << FDISK_CMDS
g
n

1MiB
+$BOOT_SIZE
n
2

+$ROOT_SIZE
n
3

+$SWAP_SIZE
n
4


FDISK_CMDS

