#!/bin/sh

root=$(git root) &&


# -- SPECS --

. $root/vm/specs &&


# -- CREATE VM --

vboxmanage createvm \
    --name $NAME \
    --ostype $TYPE \
    --register &&

vboxmanage modifyvm $NAME \
    --firmware $FIRMWARE \
    --cpus $CPUS \
    --memory $RAM \
    --vram $VRAM \
    --graphicscontroller VMSVGA &&

vboxmanage storagectl $NAME \
    --name "$SATA" \
    --add sata \
    --bootable on &&


# -- ADD DISK --

vboxmanage createhd \
    --filename $DISK \
    --size $SIZE \
    --variant standard &&

vboxmanage storageattach $NAME \
    --storagectl "$SATA" \
    --port 0 \
    --device 0 \
    --type hdd \
    --medium $DISK &&


# -- ADD IMAGE --

vboxmanage storageattach $NAME \
    --storagectl "$SATA" \
    --port 1 \
    --device 0 \
    --type dvddrive \
    --medium $root/image.iso &&


# -- MOUSE CAPTURE --

vboxmanage setextradata $NAME GUI/MouseCapturePolicy Disabled

