#!/bin/sh


# -- VARIABLES --

. $(git root)/vm/specs


# -- DELETE VM --

echo "Delete vm $NAME."

vboxmanage unregistervm --delete $NAME


# -- DELETE DISK --

echo "Delete disk $DISK."

vboxmanage closemedium disk $DISK --delete

