#!/bin/sh


# -- VARIABLES --

. $(git root)/vm/specs


# -- DELETE DISK --

vboxmanage storageattach $NAME \
    --storagectl "$SATA" \
    --port 0 --device 0 \
    --medium none

vboxmanage closemedium disk $DISK --delete


# -- DELETE VM --

vboxmanage unregistervm --delete $NAME

