#!/bin/bash


# -- BLOCK DEVICES --

echo -e "\nBlock devices:"
lsblk


# -- USER PROMPT --

echo -e "\n"

while true
do
    read -p "Enter target block device: " device

    if [[ ${#device} -ne 3 ]]; then
        echo -e "Please enter a device from the list."
        continue
    fi

    if [[ $device != sd* ]]; then
        echo -e "Please enter a device from the list."
        continue
    fi

    check=$(lsblk | grep $device)
    if [[ -z "${check// }" ]]; then 
        echo -e "Please enter a device from the list."
        continue
    fi

    break
done


# -- CONFIRMATION --

while true
do
    read -p "Are you sure you want to use /dev/$device? (y/N) " answer

    case $answer in
        [yY]* ) break;;
        [nN]* ) exit;;
        * ) continue;;
    esac
done


# -- DISK DESTROYER --

sudo dd if=./image.iso of=/dev/$device status="progress"

