#!/bin/bash


## PARTITIONS ##

BOOT_SIZE="200MiB"
SWAP_SIZE="4GiB"
ROOT_SIZE="20GiB"


## LOCALE ##

KEYMAP="de-latin1-nodeadkeys"
TIMEZONE="Europe/Berlin"
LANG="de_DE.UTF-8"


## DEVICE & USER ##

HOSTNAME="PC"
USER="david"

